from manim import *
import os

PATH_IMAGE_RAW = None

PATH_TENSOR_32_BOX = None
PATH_TENSOR_32_CLS = None

PATH_TXT_DECODE = None

PATH_TXT_RES = None

# INIT_WIDTH_IMAGE_RAW = 5
# INIT_WIDTH_IMAGE_ANNOTATION = 5

INIT_POS_IMAGE_RAW = ORIGIN
INIT_WIDTH_IMAGE_RAW = 5

INIT_POS_ANNOTATION_FINAL = ORIGIN
INIT_WIDTH_ANNOTATION_FINAL = 5

# FOCUS_WIDTH_IMAGE_RAW = 8
# FOCUS_WIDTH_IMAGE_ANNOTATION = 8

INIT_POS_IMAGE_RAW = ORIGIN
INIT_POS_TILE_INPUT = DOWN*10
INIT_POS_LF_INPUT_RAW = DOWN*10

INIT_POS_ANNOTATION_REPAD = UP*10
INIT_POS_LF_OUTPUT_REPAD = DOWN*10

INIT_POS_ANNOTATION_FINAL = ORIGIN
INIT_POS_TILE_OUTPUT = DOWN*10
INIT_POS_LF_OUTPUT_FINAL = DOWN*10

INIT_POS_AC_AB = UP*10
INIT_POS_AC_BC = UP*10
INIT_POS_AC_WX = UP*10
INIT_POS_AC_XY = UP*10
INIT_POS_AC_YZ = UP*10

INIT_POS_AC_A1 = LEFT*10
INIT_POS_AC_B2 = RIGHT*10
INIT_POS_AC_C3 = RIGHT*10
INIT_POS_AC_V5 = RIGHT*10
INIT_POS_AC_W6 = RIGHT*10
INIT_POS_AC_X7 = RIGHT*10
INIT_POS_AC_Y8 = RIGHT*10
INIT_POS_AC_Z9 = RIGHT*10

INIT_POS_AC_12 = DOWN*10
INIT_POS_AC_23 = DOWN*10
INIT_POS_AC_GAME = ORIGIN
INIT_WIDTH_AC_GAME = 1.0
INIT_POS_AC_67 = DOWN*10
INIT_POS_AC_78 = DOWN*10
INIT_POS_AC_89 = DOWN*10

# scene init related
CONFIG_DIR = 'config'
S001_IMAGE_RAW = os.path.join(CONFIG_DIR, 's001_image_raw.txt',)
S002_ANNOTATION_FINAL = os.path.join(CONFIG_DIR, 's002_annotation_final.txt',)
S003_ANNOTATION_REPAD = os.path.join(CONFIG_DIR, 's003_annotation_repad.txt')