from manim import *

PATH_IMAGE_RAW = None

PATH_TENSOR_32_BOX = None
PATH_TENSOR_32_CLS = None

PATH_TXT_DECODE = None

PATH_TXT_RES = None

INIT_WIDTH_IMAGE_RAW = 5
INIT_WIDTH_IMAGE_ANNOTATION = 5

FOCUS_WIDTH_IMAGE_RAW = 8
FOCUS_WIDTH_IMAGE_ANNOTATION = 8

INIT_SHIFT_TILE_INPUT = DOWN*10
INIT_SHIFT_TILE_OUTPUT = DOWN*10

INIT_SHIFT_AC_AB = UP*10
INIT_SHIFT_AC_WX = UP*10
INIT_SHIFT_AC_XY = UP*10
INIT_SHIFT_AC_YZ = UP*10

INIT_SHIFT_AC_A1 = LEFT*10
INIT_SHIFT_AC_B2 = LEFT*10
INIT_SHIFT_AC_V5 = RIGHT*10
INIT_SHIFT_AC_W6 = RIGHT*10
INIT_SHIFT_AC_X7 = RIGHT*10
INIT_SHIFT_AC_Y8 = RIGHT*10
INIT_SHIFT_AC_Z9 = RIGHT*10

INIT_SHIFT_AC_12 = DOWN*10
INIT_SHIFT_AC_23 = DOWN*10
INIT_SHIFT_AC_GAME = ORIGIN
INIT_SHIFT_AC_67 = DOWN*10
INIT_SHIFT_AC_78 = DOWN*10
INIT_SHIFT_AC_89 = DOWN*10
